travis:
  secure:
    BINSTAR_TOKEN: ikAsMXnhv+p8pxdjUqEHfYAbTdWuTFxgzinUV0tZ9tvA7QBVx6WKkp7Iyr6Yd+3YA6lrN/bBqf3KFlyrVmFwjS2M4N7zT2Ddxj5BmT/UuW0pN6y2WAkuSla+OpDG0xkxz6aiUA55j/1xPcItDmXnJFObj3ucSGRNw8nFynBu/lVYn/6wJUPEVbtOb4ertjriQtypAWpGhxqhhDsN1sp0yP7PKfcW16YRJVkc4NR5OzrZhXOvq1XJ621CudXMM14QJXylPBKggo7+bTKOpjyBe1HD1ZWVORMHXkM6zterMVqUqR2QI0b6rdNtdGy0wKz90njhk71CJXpUEsdcjjqZqiotfTGSgfG8/wphX/10WvQ9CmgBmNRLgKe+Y97Vs0KwI5mSfxdcWmCoKcgUzEOyjC/FWLBrVh0LY/u5j1KsaFr9p/UnuvcOtjmQKHDtMQD7hB+34M+3lEEdizsG60g6GCx8SKBPCWMtENIVuyYEl5bq9YmAqKHwtcLvx6DTCOw6kqWh7r+0gXeQr2Ui3M2JM3AqWODp8LJ5chmqitJ0r+0OIlHpUBH8e+ZBdAEbSvEyEB+B004CnExZyhEuZoqv5+izsjZ9GqiEaRC0so690XhJAjjs6rqwLJh2gViOwGuoB/ffpvOpWbUuFLrPsyIyFWH7ZP3u9CkSU2mfYmoRTHg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
